# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-10 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180310_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candles',
            name='timestamp',
            field=models.IntegerField(),
        ),
    ]
