# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-24 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180324_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='validations',
            old_name='result',
            new_name='algorithm',
        ),
        migrations.RemoveField(
            model_name='validations',
            name='typ',
        ),
        migrations.AddField(
            model_name='validations',
            name='accuracy',
            field=models.DecimalField(decimal_places=10, default='-1.0000000000', max_digits=20),
        ),
        migrations.AddField(
            model_name='validations',
            name='adaptability',
            field=models.DecimalField(decimal_places=10, default='-1.0000000000', max_digits=20),
        ),
        migrations.AddField(
            model_name='validations',
            name='timestamp',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='validations',
            name='timetotrain',
            field=models.DecimalField(decimal_places=10, default='-1.0000000000', max_digits=20),
        ),
    ]
